# Generated by Django 5.0.13 on 2025-11-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):



    dependencies = [
        ('analytics', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartactivitylog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
