# Generated by Django 5.0.13 on 2025-11-04 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):



    dependencies = [
        ('users', '0001_initial'),  # Ensure users table is created first
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartactivitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product'),
        ),
        migrations.AddField(
            model_name='productview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cartactivitylog',
            index=models.Index(fields=['-created_at'], name='cart_activi_created_e68780_idx'),
        ),
        migrations.AddIndex(
            model_name='cartactivitylog',
            index=models.Index(fields=['user', '-created_at'], name='cart_activi_user_id_101775_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product', '-viewed_at'], name='product_vie_product_e08eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['session_id'], name='product_vie_session_0d7382_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['-searched_at'], name='search_quer_searche_a756a3_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['query'], name='search_quer_query_50e46f_idx'),
        ),
    ]
