# Generated by Django 5.0.13 on 2025-10-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_average_rating_product_review_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deletion_requested',
            field=models.BooleanField(default=False, help_text='Request for product deletion pending admin approval'),
        ),
        migrations.AddField(
            model_name='product',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the deletion was requested', null=True),
        ),
    ]
